version: '3.4'
services:

  development:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/vscode:cached
      # Give access to ssh keys on the host (Is there a better way to do this?)
      - ~/.ssh:/home/host-ssh:cached
      # We need this so docker in docker works (Check this)
      - /var/run/docker.sock:/var/run/docker.sock
      - target:/vscode/target # Set target as a volume for performance. 
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    working_dir: /vscode
volumes:
  target:
  #node_modules: